### ISSUE TITLE
Add ability to create, update, delete and list projects.

### ISSUE THREAD

**Issue by wlan0** [rancher/cattle#122]
1. GET /v1/project should allow a user to list all the projects that he has access to
2. POST/DELETE/PUT should work similarly for creating, deleting and updating a project 
3. The creator of the project should be able to limit the scope of a project to themselves, a github organization that they are a part of or a github team within a github organization  that they have write access to

**Comment by deniseschannon** [comment]
This is implemented and now called "environments".
