### ISSUE TITLE
Add project based auth

### ISSUE THREAD

**Issue by wlan0** [rancher/cattle#123]
1. Store the list of projectIds that a user has access to, into the jwt token during the creation of the token.
2. Look for X-PROJECT-ID header in a request. 
3. If the header is present, use the token to validate if the user for the project

This is a sub task of #122

**Comment by vincent99** [comment]
Stuff I found playing with the API, please make sure we add tests for these too.

- [ ] The `type` of a project should be `project`, not `account`
- [ ] `kind`, `uuid`, etc should not be createable on a project
- [ ] Schema for project's `externalIdType` should be an enum of valid choices
- [ ] After creating a project the `externalId` changes from a team/org name to the github id.  The public API should only be dealing with names
- [ ] `POST /v1/token` looks at other `Authorization` headers and returns 404 if their auth fails
- [ ] Invalid `x-api-project-id:` should return 401, not 500
- [ ] `/v1/subscribe` needs to take project id as a query param, `project_id=1a8`
- [ ] `x-api-project-id:` header needs to accept an obfuscated IDs
- [ ] Can't get anything with a valid `x-api-project-id:` header set

**Comment by sidharthamani** [comment]
[] the externalId on /v1/projects should be obfuscated if they are accountIds

**Comment by vincent99** [comment]
?  GitHub account ids stored in externalId don't need to be obfuscated

**Comment by ibuildthecloud** [comment]
Don't obfuscate github Ids.   Can the param to subscribe be projectId?

**Comment by vincent99** [comment]
Yes, `?projectId=1a8` is better

**Comment by deniseschannon** [comment]
Exists today but called environments in the UI.
