### ISSUE TITLE
haproxy restarts for ever

### ISSUE THREAD

**Issue by haswalt** [rancher/cattle#1294]
I hit a bug yesterday with a load balancer instance on 1 host. It only happened on one host so far and i'm not sure if it's related to #1279 but:

3 hosts running load balancer in global mode.
host 1 constantly restarts HAProxy even when it's already running.
host 1 ends up with 75 haproxy processes running in about 30 minutes.
host 1 hits load of 75 then dies.

Running rancher v0.51.0

**Comment by deniseschannon** [comment]
If you are still seeing this issue with a later version of Rancher, could you open a new issue in rancher/rancher? I'm closing the issues for this repo so we can consolidate everything into Rancher.

**Comment by deniseschannon** [comment]
Also, we've update the version of HAproxy in our most recent release, so please let us know what version  you are running if you open a new issue. Thank you!
