### ISSUE TITLE
LDAP - Group's members identification

### ISSUE THREAD

**Issue by ViBiOh** [rancher/cattle#1306]
Hi,

I'm currently looking to set Access Control with OpenLDAP on Docker Rancher Server. Mapping of Users was made but identifying them into groups for easy environment configuration doesn't work.

After search, I found that piece of code in OpenLDAPIdentityProvider and requests seems wrong to me.

```java
if (memberOf != null) {// null if this user belongs to no group at all
    for (int i = 0; i < memberOf.size(); i++) {
        identities.addAll(resultsToIdentities(searchLdap("(&(" + getConstantsConfig().getUserMemberAttribute() +
                '=' + memberOf.get(i).toString() + ")(" + getConstantsConfig().objectClass() + '=' +
                getConstantsConfig().getGroupObjectClass() + "))")));

    }
}
```

For example, this will generate `(& (memberOf=CN_OF_MY_GROUP) (objectclass=group))` but there is no attribute named `memberOf` on Groups. The same attribute name `getUserMemberAttribute` is used for both User and Groups mapping.

From my point of view, `memberOf` must be replaced by `distinguishedName` or a configurable value

Below code (next to the first), is trying to do the inverse but again, `getLogin` doesn't match our expectations, we store DN inside `member` attribute of Groups.

```java
if (user != null && StringUtils.isNotBlank(user.getLogin())){
    String query = "(&(" + getConstantsConfig().getGroupMemberMappingAttribute()
            + '=' + user.getLogin()
            + ")(" + getConstantsConfig().objectClass() + '='
            + getConstantsConfig().getGroupObjectClass() + "))";
    identities.addAll(resultsToIdentities(searchLdap(query)));
}
```

Am I wrong ?

**Comment by deniseschannon** [comment]
Closed in favor of https://github.com/rancher/rancher/issues/3875
