### ISSUE TITLE
Something wrong in code\packaging\app\src\main\webapp\WEB-INF\web.xml ?

### ISSUE THREAD

**Issue by kingsmiler** [rancher/cattle#1318]
In the web.xml, the web-app header is :

> 

<web-app xmlns="http://java.sun.com/xml/ns/javaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_3_1.xsd"
    version="3.1" metadata-complete="true" >

> 

the version is 3.1, but the head is not follow the spec3.1.

<web-app xmlns="http://xmlns.jcp.org/xml/ns/javaee"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee
                      http://xmlns.jcp.org/xml/ns/javaee/web-app_3_1.xsd"
         version="3.1" metadata-complete="true" >

**Comment by ibuildthecloud** [comment]
Do you want to put in a PR to fix this?

**Comment by kingsmiler** [comment]
Yeah, I'd like to. There are three web.xml in cattle maybe need to be fixed.

**Comment by kingsmiler** [comment]
I like cattle, so i hope to do something i can.

**Comment by deniseschannon** [comment]
Moved to https://github.com/rancher/rancher/issues/3870 and linked the open PR.
