### ISSUE TITLE
There are 3 spring version in cattle, is there some plan to resolve?

### ISSUE THREAD

**Issue by kingsmiler** [rancher/cattle#1323]
code/meta-parent/pom.xml
<spring.version>3.2.4.RELEASE</spring.version>

code/framework/metrics/pom.xml
<dependency>
    <groupId>com.ryantenney.metrics</groupId>
    <artifactId>metrics-spring</artifactId>
    <version>3.0.0-RC4</version>
</dependency>

spring3.2.5

<dependency>
    <groupId>fr.xebia.management</groupId>
    <artifactId>xebia-management-extras</artifactId>
    <version>1.2.3</version>
</dependency>

spring3.1.3

**Comment by deniseschannon** [comment]
Closed in favor of https://github.com/rancher/rancher/issues/3871
