### ISSUE TITLE
Add hosts summary API

### ISSUE THREAD

**Issue by vincent99** [rancher/cattle#137]
Add a `/v1/hostsSummary` API to return aggregated data that the UI needs to efficiently display the new Hosts screen:

```javascript
{
  type: 'collection',
  resourceType: 'hostSummary',

  data: [
    {
      id: '1h1',
      type: 'hostSummary'

      name: 'nyc3-node/docker',
      description: 'blah',
      zoneId: '1z1',

      // If there are multiple, the first/primary IP?
      ipAddress: '123.123.123.123',

      // Combination of host state + agent state? (host.state == 'active' ? agent.state : host.state)
      state: 'active',

      // For hosts that are a swarm cluster, the number of hosts in the swarm.  This will always be null until swarm support is added.
      clusterSize: null,
      
      // The actions available to the host
      actions: {
        deactivate: '...?action=deactivate',
        ...
      },

      // Count of instances on the host, grouped by instance state
      instanceStates: {
        running: 101,
        stopped: 20,
        stopping: 2,
        starting: 3,
        ...
      },

      links: {
        self: '...',
        agent: '.../agent',
        host: '.../host',
        instances: '.../instances',
        zone: '.../zone',
      }
    },

    ... more host summaries ...
  ]
}
```

**Comment by ibuildthecloud** [comment]
@vincent99 and the corresponding SQL....

**Comment by vincent99** [comment]
You probably don't want it in one query and getting back a copy of the host for each state, so first do the normal query for `GET /v1/hosts`, but with only the relevant fields..

Then something like

```sql
SELECT 
  host.id AS host_id,
  instance.state,
  COUNT(*) AS 'count'
FROM host 
  JOIN instance_host_map ihm ON (ihm.host_id = host.id)
  JOIN instance ON (ihm.instance_id = instance.id)
WHERE 
  host.account_id = '4'
GROUP BY host.id, instance.state;
```

and map the counts into the host objects.

**Comment by ibuildthecloud** [comment]
That seems simple enough.  I probably won't have time to do this until Wednesday but it should be straight forward.

**Comment by ibuildthecloud** [comment]
If I combine the host and agent state, as state changes on the agent or host, will you track it properly still.

**Comment by vincent99** [comment]
If there are resource change events for the hostSummary then it would update automatically.. If not then I could watch for agent/host changes and update the affected summary resource in memory.  In that case it would be better if you return separate hostState and agentState properties and I'll do the combining of them.

**Comment by ibuildthecloud** [comment]
Right now I'd prefer to return them separate.  What I think the better long term solution is that I tie agent state to host internally such that if the agent goes down we mark the host unavailable.  In that case you would only care about host state.

**Comment by ibuildthecloud** [comment]
- [ ] Support get host summary by id
