### ISSUE TITLE
Users can't see agents so host state is wrong

### ISSUE THREAD

**Issue by ibuildthecloud** [rancher/cattle#173]
Currently the host state in the UI is a combination of the host state and the agent state.  For a normal user they can't see that agent.  The host state should be tied to the agent state such that if the agent state is not active the host shows that.

**Comment by vincent99** [comment]
Patched in the UI to fall back to host state if no agent state is available for now..

**Comment by ibuildthecloud** [comment]
A possible solution is to add the agent state to the host object.  Actually combining the two states of host and agent will become problematic.  If this approach is done it is important that resource.change events are still fired for a host whenever an agent changes.
