### ISSUE TITLE
Forwarding rule is set in CATTLE_POSTROUTING iptables chain for container on Unmanaged

### ISSUE THREAD

**Issue by alena1108** [rancher/cattle#182]
When create container on unamanged network with port bindings, iptables rule is created in CATTLE_POSTROUTING instead of a DOCKER chain

Chain CATTLE_PREROUTING (1 references)
target     prot opt source               destination
..................
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL tcp dpt:444 to:172.17.0.13:444

**Comment by jangrewe** [comment]
I'm having the same issue with Shorewall and the scripts from this page:

http://blog.discourse.org/2015/11/shorewalldocker-two-great-tastes-that-taste-great-together/

**Comment by deniseschannon** [comment]
Closed in favor of Rancher/rancher#3843
