### ISSUE TITLE
PUT to activeSettings saves the new value but returns the old one

### ISSUE THREAD

**Issue by vincent99** [rancher/cattle#234]
1. `GET /v1/activeSettings/blah` responds with `{..., value: 'a'}`
2. `PUT /v1/activeSettings/blah` with `{value: 'b'}` responds with `{..., value: 'a'}`
3. A subsequent `GET /v1/activeSettings/blah` then responds with `{..., value: 'b'}`

PUT should return the new value.

(`blah` in this case was 1as!api.ui.js.url)

**Comment by ibuildthecloud** [comment]
I surprised it even changes the value....

**Comment by deniseschannon** [comment]
Closed in favor of rancher/rancher#3853
