### ISSUE TITLE
Modify docker allocator logic to account for volumesFrom

### ISSUE THREAD

**Issue by cjellick** [rancher/cattle#24]
When we added the volumesFrom functionality, we did not attempt to add logic to the allocator to account for it.

We should add logic such that:
1. If a host is specified and one or more volumesFrom container ids is specified, the allocator validates that that host is currently running the specified volumesFrom containers.
2. If a host is ***not*** specified and one or more volumesFrom container ids is specified, the allocator selects the host that is hosting all the specified volumesFrom containers. If no host meets this criteria, raise an allocation error.

**Comment by deniseschannon** [comment]
Sidekicks are required to support containers/services using `volumesFrom`
