### ISSUE TITLE
Logs: first n lines all come in one frame

### ISSUE THREAD

**Issue by vincent99** [rancher/cattle#249]
The inital backlog of `lines` lines are all delivered as one big websocket frame full of newlines.  Can they be split up into individual frames like all the subsequent messages are so the client doesn't have to sub-divide the frames?

**Comment by hibooboo2** [comment]
This is done from the docker client api. I will look into possible modifying the client and submitting a pr to the go docker client. But it is not something i can change within my code.

**Comment by vincent99** [comment]
I guess this really belongs in host-api instead of here, but why can't you receive the output stream from the dockerClient yourself and process into separate frames instead of directly hooking `logOptions.OutputStream` to the websocket `conn`?

**Comment by ibuildthecloud** [comment]
@hibooboo2 you need to create your own Writer that looks at the content, splits it up and then call write individually on the websocket.

**Comment by hibooboo2** [comment]
Ok i will look into it.


On Sun, Feb 8, 2015 at 6:57 AM, Darren <notifications@github.com> wrote:

> @hibooboo2 <https://github.com/hibooboo2> you need to create your own
> Writer that looks at the content, splits it up and then call write
> individually on the websocket.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rancherio/cattle/issues/249#issuecomment-73411806>.
>



-- 

******************************************************

James Harris, Software Engineer

Tempe, AZ 85281

Tel: (480)-255-0632 (M), (480) 269-7232 (Google voice)

E-mail: wizardofmath@gmail.com

******************************************************

**Comment by deniseschannon** [comment]
Closed in favor of rancher/rancher#3854
