### ISSUE TITLE
Output type for register actions is "GenericObject"

### ISSUE THREAD

**Issue by cjellick** [rancher/cattle#251]
This may not be a bug, but it doesn't match the common pattern of the output type matching the resource type for "simple" actions. Also, GenericObject doesn't appear to be an available schema type.

**Comment by ibuildthecloud** [comment]
This is a bug.  Projects suffered from the same thing.  It's a simple fix.

**Comment by ibuildthecloud** [comment]
This is a bug.  Projects suffered from the same thing.  It's a simple fix.

**Comment by deniseschannon** [comment]
Closed in favor of rancher/rancher#3856
