### ISSUE TITLE
Tests use non rancher images.

### ISSUE THREAD

**Issue by hibooboo2** [rancher/cattle#269]
The integration tests currently use images that are on repos that are not from the rancher account. They should only use images from rancher.

**Comment by ibuildthecloud** [comment]
Are you referring to ibuildthecloud/* images?  Are their other images?  I'll gladly move them.

**Comment by cjellick** [comment]
There's one from my repo as well for the volume tests.

**Comment by hibooboo2** [comment]
Both

**Comment by deniseschannon** [comment]
Closed in favor of rancher/rancher#3858
