### ISSUE TITLE
Feature request: Fail fast if -Dagent.package.python.agent.url points to a non-existent path

### ISSUE THREAD

**Issue by sonchang** [rancher/cattle#301]
Current behavior just causes an error and infinite loop in the rancher-agent container

**Comment by ibuildthecloud** [comment]
Can you give a bit more context, maybe a specific example?

**Comment by sonchang** [comment]
Just updated the title.  Sorry.  Just realized the original title was confusing.

**Comment by ibuildthecloud** [comment]
Ah yes, that is a good idra

**Comment by deniseschannon** [comment]
Closed in favor of rancher/rancher#3859
