### ISSUE TITLE
Integrate Docker Machine into Rancher

### ISSUE THREAD

**Issue by cjellick** [rancher/cattle#65]
Allow users to create new hosts via the Rancher API instead of having to run ```docker run rancher-agent...``` on an existing host.

## UI
In the UI, the user should be able to access an "Add Host" widget that allows them to create new hosts on certain supported cloud providers.

## API
To support this in the UI, we'll add a new resource called ```dockerMachine``` in the the API. This resource will be a special kind of ```physicalHost``` with additional properties to support all the driver configuration options available in docker-machine.

## Architecture
Will require a new event listener that listens for and reacts to ```dockerMachine``` life cycle events. Here is what it will do at each step in the life cycle:
* On ```create```, exec out to the docker-machine binary to create the host. Once the create completes successfully, access the machine's config.json and push it into the rancher resource.
* On ```activate```, utilize the docker-machine to  obtain connection information to the docker daemon for the host and execute the equivalent of ```docker run rancher-agent...``` on the host.
* On ```delete```, exec out to the docker-machine binary to delete the host.

This agent will run next to the rancher-server. So, one cluster per rancher-server cluster, not one per account or user.

## Open questions
* How do we handle the loss of the machine agent? Docker-machine maintains state on disk, so if we lose the agent, we'll lose the state that allows us to access and CRUD the hosts.
* How do we deal with security concerns? Docker-machine stores cloud credentials in the config.json so that it can later operate on a host. What kind of security concerns/risks does this introduce and how do we mitigate?

**Comment by will-chan** [comment]
How does the DB schema look like for this since you are assuming a single machine-agent per rancher-server?

**Comment by deniseschannon** [comment]
Already added into Rancher
