### ISSUE TITLE
Database schema testing

### ISSUE THREAD

**Issue by dx9** [rancher/cattle#678]
A test that verifies the schema build against different databases. Does this exist already? Has anyone thought about it?

**Comment by ibuildthecloud** [comment]
We run full tests against MySQL and light integration tests against H2.  Id love to do the same for Postgres.  The changes need to be done some where in the test script in cattle.

**Comment by ibuildthecloud** [comment]
I'd look at https://github.com/rancher/cattle/blob/master/scripts/ci to see how H2 is done.

**Comment by dx9** [comment]
cool I'll take a look
