### ISSUE TITLE
Enhancement: Add Token type

### ISSUE THREAD

**Issue by ibuildthecloud** [rancher/cattle#71]
Add a new type for token.  You follow io.cattle.platform.extension.api.model.ResourceDefinition as an example.

- [ ] Create simple Token POJO
- [ ] Register in an appropriate spring XML using code/implementation/extension-api/src/main/resources/META-INF/cattle/extension-api/spring-extension-api-context.xml as an example (You need to create a TypeSet object)

Sub task of https://github.com/rancherio/cattle/issues/62

**Comment by deniseschannon** [comment]
Closed in favor of rancher/rancher#3829
