### ISSUE TITLE
Enhancement : API for authentication configuration

### ISSUE THREAD

**Issue by wlan0** [rancher/cattle#89]
Create a API  `POST /v1/githubconfig` that a client can use to configure authentication.

The POST body will contain the following information
```json
{ 
    "type": "githubConfig",
    "enabled": true,
    "clientId": "1234556",
    "clientSecret": "123456",
    "allowUsers": ["username1","username2"],
    "allowOrganizations": ["org1","org2"]
}
```

This is a subtask of #62

**Comment by deniseschannon** [comment]
Closed in favor of rancher/rancher#3832
