### ISSUE TITLE
Feature: API authentication

### ISSUE THREAD

**Issue by pranavs18** [rancher/cattle#97]
1) Add the new set of permissions for admin/user 
2) Write integration tests to support the new set of permissions
3) Add a new legacy admin client to support the already existing tests which might fail because of the new set of permissions.

**Comment by pranavs18** [comment]
PR submitted here - https://github.com/rancherio/cattle/pull/61

**Comment by pranavs18** [comment]
PR submitted again with the new admin_client tests and support for an internal admin client for the tests related to "resource types/fields" we don't intend to expose to the admin/user like nics, ipsec, storagePool etc. https://github.com/rancherio/cattle/pull/61

**Comment by deniseschannon** [comment]
Closed in favor of rancher/rancher#3833
